# Generated by Django 4.0.6 on 2022-10-17 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Printer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Printer name', max_length=64)),
                ('api_key', models.CharField(help_text='API access key', max_length=128, unique=True)),
                ('check_type', models.CharField(choices=[('KT', 'Kitchen'), ('CL', 'Client')], default='KT', help_text='The type of receipt printed by the printer', max_length=2)),
                ('point_id', models.IntegerField(help_text='The point to which the printer is bound')),
            ],
        ),
    ]
