# Generated by Django 4.0.6 on 2022-10-17 13:32

import api.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Check',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('KT', 'Kitchen'), ('CL', 'Client')], default='KT', help_text='Type check', max_length=2)),
                ('order', models.JSONField(help_text='order information')),
                ('status', models.CharField(choices=[('NW', 'New'), ('RD', 'Rendered'), ('PD', 'Printed')], default='NW', help_text='Check status', max_length=2)),
                ('pdf_file', models.FileField(help_text='link to created PDF file', max_length=1024, upload_to=api.models.user_directory_path)),
                ('printer_id', models.ForeignKey(help_text='printer', on_delete=django.db.models.deletion.CASCADE, to='api.printer')),
            ],
        ),
    ]
